//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Finanace_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class expens
    {
        public int expense_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<System.DateTime> expense_date { get; set; }
        public string expence_category { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> ammount { get; set; }
    
        public virtual account account { get; set; }
        public virtual user user { get; set; }
    }
}
