//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Finanace_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class librarye
    {
        public int Roll_no { get; set; }
        public string name { get; set; }
        public Nullable<int> student_id { get; set; }
    
        public virtual @class @class { get; set; }
    }
}
