//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Finanace_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Personal_Finance_Management_SystemEntities : DbContext
    {
        public Personal_Finance_Management_SystemEntities()
            : base("name=Personal_Finance_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<budget> budgets { get; set; }
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<expens> expenses { get; set; }
        public virtual DbSet<income> incomes { get; set; }
        public virtual DbSet<income_source> income_source { get; set; }
        public virtual DbSet<librarye> libraryes { get; set; }
        public virtual DbSet<target_amount> target_amount { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<expense_category> expense_category { get; set; }
    }
}
